/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PolicyRouteImport } from './app/policy'
import { Route as GoodbyeRouteImport } from './app/goodbye'
import { Route as ChatRouteImport } from './app/_chat'
import { Route as AuthRouteImport } from './app/_auth'
import { Route as ChatIndexRouteImport } from './app/_chat/index'
import { Route as PolicyTermsRouteImport } from './app/policy/terms'
import { Route as PolicyPrivacyRouteImport } from './app/policy/privacy'
import { Route as ApiUploadthingRouteImport } from './app/api/uploadthing'
import { Route as ApiMailRouteImport } from './app/api/mail'
import { Route as ChatXrRouteImport } from './app/_chat/xr'
import { Route as ChatPricingRouteImport } from './app/_chat/pricing'
import { Route as ChatAuthenticatedRouteImport } from './app/_chat/_authenticated'
import { Route as AuthSignUpRouteImport } from './app/_auth/sign-up'
import { Route as AuthLoginRouteImport } from './app/_auth/login'
import { Route as ChatAuthenticatedSettingsRouteImport } from './app/_chat/_authenticated/settings'
import { Route as ChatAuthenticatedNewRouteImport } from './app/_chat/_authenticated/new'
import { Route as ChatAuthenticatedSettingsIndexRouteImport } from './app/_chat/_authenticated/settings/index'
import { Route as ChatAuthenticatedSettingsPreferencesRouteImport } from './app/_chat/_authenticated/settings/preferences'
import { Route as ChatAuthenticatedSettingsContactRouteImport } from './app/_chat/_authenticated/settings/contact'
import { Route as ChatAuthenticatedSettingsAccountRouteImport } from './app/_chat/_authenticated/settings/account'
import { Route as ChatAuthenticatedChatIdRouteImport } from './app/_chat/_authenticated/chat.$id'

const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodbyeRoute = GoodbyeRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const PolicyTermsRoute = PolicyTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PolicyRoute,
} as any)
const PolicyPrivacyRoute = PolicyPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PolicyRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailRoute = ApiMailRouteImport.update({
  id: '/api/mail',
  path: '/api/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatXrRoute = ChatXrRouteImport.update({
  id: '/xr',
  path: '/xr',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPricingRoute = ChatPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAuthenticatedRoute = ChatAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ChatRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ChatAuthenticatedSettingsRoute =
  ChatAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ChatAuthenticatedRoute,
  } as any)
const ChatAuthenticatedNewRoute = ChatAuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ChatAuthenticatedRoute,
} as any)
const ChatAuthenticatedSettingsIndexRoute =
  ChatAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChatAuthenticatedSettingsRoute,
  } as any)
const ChatAuthenticatedSettingsPreferencesRoute =
  ChatAuthenticatedSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => ChatAuthenticatedSettingsRoute,
  } as any)
const ChatAuthenticatedSettingsContactRoute =
  ChatAuthenticatedSettingsContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => ChatAuthenticatedSettingsRoute,
  } as any)
const ChatAuthenticatedSettingsAccountRoute =
  ChatAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => ChatAuthenticatedSettingsRoute,
  } as any)
const ChatAuthenticatedChatIdRoute = ChatAuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => ChatAuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/goodbye': typeof GoodbyeRoute
  '/policy': typeof PolicyRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/pricing': typeof ChatPricingRoute
  '/xr': typeof ChatXrRoute
  '/api/mail': typeof ApiMailRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/policy/privacy': typeof PolicyPrivacyRoute
  '/policy/terms': typeof PolicyTermsRoute
  '/new': typeof ChatAuthenticatedNewRoute
  '/settings': typeof ChatAuthenticatedSettingsRouteWithChildren
  '/chat/$id': typeof ChatAuthenticatedChatIdRoute
  '/settings/account': typeof ChatAuthenticatedSettingsAccountRoute
  '/settings/contact': typeof ChatAuthenticatedSettingsContactRoute
  '/settings/preferences': typeof ChatAuthenticatedSettingsPreferencesRoute
  '/settings/': typeof ChatAuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ChatIndexRoute
  '/goodbye': typeof GoodbyeRoute
  '/policy': typeof PolicyRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/pricing': typeof ChatPricingRoute
  '/xr': typeof ChatXrRoute
  '/api/mail': typeof ApiMailRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/policy/privacy': typeof PolicyPrivacyRoute
  '/policy/terms': typeof PolicyTermsRoute
  '/new': typeof ChatAuthenticatedNewRoute
  '/chat/$id': typeof ChatAuthenticatedChatIdRoute
  '/settings/account': typeof ChatAuthenticatedSettingsAccountRoute
  '/settings/contact': typeof ChatAuthenticatedSettingsContactRoute
  '/settings/preferences': typeof ChatAuthenticatedSettingsPreferencesRoute
  '/settings': typeof ChatAuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_chat': typeof ChatRouteWithChildren
  '/goodbye': typeof GoodbyeRoute
  '/policy': typeof PolicyRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_chat/_authenticated': typeof ChatAuthenticatedRouteWithChildren
  '/_chat/pricing': typeof ChatPricingRoute
  '/_chat/xr': typeof ChatXrRoute
  '/api/mail': typeof ApiMailRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/policy/privacy': typeof PolicyPrivacyRoute
  '/policy/terms': typeof PolicyTermsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/_authenticated/new': typeof ChatAuthenticatedNewRoute
  '/_chat/_authenticated/settings': typeof ChatAuthenticatedSettingsRouteWithChildren
  '/_chat/_authenticated/chat/$id': typeof ChatAuthenticatedChatIdRoute
  '/_chat/_authenticated/settings/account': typeof ChatAuthenticatedSettingsAccountRoute
  '/_chat/_authenticated/settings/contact': typeof ChatAuthenticatedSettingsContactRoute
  '/_chat/_authenticated/settings/preferences': typeof ChatAuthenticatedSettingsPreferencesRoute
  '/_chat/_authenticated/settings/': typeof ChatAuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goodbye'
    | '/policy'
    | '/login'
    | '/sign-up'
    | '/pricing'
    | '/xr'
    | '/api/mail'
    | '/api/uploadthing'
    | '/policy/privacy'
    | '/policy/terms'
    | '/new'
    | '/settings'
    | '/chat/$id'
    | '/settings/account'
    | '/settings/contact'
    | '/settings/preferences'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/goodbye'
    | '/policy'
    | '/login'
    | '/sign-up'
    | '/pricing'
    | '/xr'
    | '/api/mail'
    | '/api/uploadthing'
    | '/policy/privacy'
    | '/policy/terms'
    | '/new'
    | '/chat/$id'
    | '/settings/account'
    | '/settings/contact'
    | '/settings/preferences'
    | '/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/_chat'
    | '/goodbye'
    | '/policy'
    | '/_auth/login'
    | '/_auth/sign-up'
    | '/_chat/_authenticated'
    | '/_chat/pricing'
    | '/_chat/xr'
    | '/api/mail'
    | '/api/uploadthing'
    | '/policy/privacy'
    | '/policy/terms'
    | '/_chat/'
    | '/_chat/_authenticated/new'
    | '/_chat/_authenticated/settings'
    | '/_chat/_authenticated/chat/$id'
    | '/_chat/_authenticated/settings/account'
    | '/_chat/_authenticated/settings/contact'
    | '/_chat/_authenticated/settings/preferences'
    | '/_chat/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
  GoodbyeRoute: typeof GoodbyeRoute
  PolicyRoute: typeof PolicyRouteWithChildren
  ApiMailRoute: typeof ApiMailRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodbye': {
      id: '/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof GoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/policy/terms': {
      id: '/policy/terms'
      path: '/terms'
      fullPath: '/policy/terms'
      preLoaderRoute: typeof PolicyTermsRouteImport
      parentRoute: typeof PolicyRoute
    }
    '/policy/privacy': {
      id: '/policy/privacy'
      path: '/privacy'
      fullPath: '/policy/privacy'
      preLoaderRoute: typeof PolicyPrivacyRouteImport
      parentRoute: typeof PolicyRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail': {
      id: '/api/mail'
      path: '/api/mail'
      fullPath: '/api/mail'
      preLoaderRoute: typeof ApiMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/xr': {
      id: '/_chat/xr'
      path: '/xr'
      fullPath: '/xr'
      preLoaderRoute: typeof ChatXrRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pricing': {
      id: '/_chat/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ChatPricingRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/_authenticated': {
      id: '/_chat/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatAuthenticatedRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_chat/_authenticated/settings': {
      id: '/_chat/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatAuthenticatedSettingsRouteImport
      parentRoute: typeof ChatAuthenticatedRoute
    }
    '/_chat/_authenticated/new': {
      id: '/_chat/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof ChatAuthenticatedNewRouteImport
      parentRoute: typeof ChatAuthenticatedRoute
    }
    '/_chat/_authenticated/settings/': {
      id: '/_chat/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ChatAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof ChatAuthenticatedSettingsRoute
    }
    '/_chat/_authenticated/settings/preferences': {
      id: '/_chat/_authenticated/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof ChatAuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof ChatAuthenticatedSettingsRoute
    }
    '/_chat/_authenticated/settings/contact': {
      id: '/_chat/_authenticated/settings/contact'
      path: '/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof ChatAuthenticatedSettingsContactRouteImport
      parentRoute: typeof ChatAuthenticatedSettingsRoute
    }
    '/_chat/_authenticated/settings/account': {
      id: '/_chat/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ChatAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof ChatAuthenticatedSettingsRoute
    }
    '/_chat/_authenticated/chat/$id': {
      id: '/_chat/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatAuthenticatedChatIdRouteImport
      parentRoute: typeof ChatAuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ChatAuthenticatedSettingsRouteChildren {
  ChatAuthenticatedSettingsAccountRoute: typeof ChatAuthenticatedSettingsAccountRoute
  ChatAuthenticatedSettingsContactRoute: typeof ChatAuthenticatedSettingsContactRoute
  ChatAuthenticatedSettingsPreferencesRoute: typeof ChatAuthenticatedSettingsPreferencesRoute
  ChatAuthenticatedSettingsIndexRoute: typeof ChatAuthenticatedSettingsIndexRoute
}

const ChatAuthenticatedSettingsRouteChildren: ChatAuthenticatedSettingsRouteChildren =
  {
    ChatAuthenticatedSettingsAccountRoute:
      ChatAuthenticatedSettingsAccountRoute,
    ChatAuthenticatedSettingsContactRoute:
      ChatAuthenticatedSettingsContactRoute,
    ChatAuthenticatedSettingsPreferencesRoute:
      ChatAuthenticatedSettingsPreferencesRoute,
    ChatAuthenticatedSettingsIndexRoute: ChatAuthenticatedSettingsIndexRoute,
  }

const ChatAuthenticatedSettingsRouteWithChildren =
  ChatAuthenticatedSettingsRoute._addFileChildren(
    ChatAuthenticatedSettingsRouteChildren,
  )

interface ChatAuthenticatedRouteChildren {
  ChatAuthenticatedNewRoute: typeof ChatAuthenticatedNewRoute
  ChatAuthenticatedSettingsRoute: typeof ChatAuthenticatedSettingsRouteWithChildren
  ChatAuthenticatedChatIdRoute: typeof ChatAuthenticatedChatIdRoute
}

const ChatAuthenticatedRouteChildren: ChatAuthenticatedRouteChildren = {
  ChatAuthenticatedNewRoute: ChatAuthenticatedNewRoute,
  ChatAuthenticatedSettingsRoute: ChatAuthenticatedSettingsRouteWithChildren,
  ChatAuthenticatedChatIdRoute: ChatAuthenticatedChatIdRoute,
}

const ChatAuthenticatedRouteWithChildren =
  ChatAuthenticatedRoute._addFileChildren(ChatAuthenticatedRouteChildren)

interface ChatRouteChildren {
  ChatAuthenticatedRoute: typeof ChatAuthenticatedRouteWithChildren
  ChatPricingRoute: typeof ChatPricingRoute
  ChatXrRoute: typeof ChatXrRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatAuthenticatedRoute: ChatAuthenticatedRouteWithChildren,
  ChatPricingRoute: ChatPricingRoute,
  ChatXrRoute: ChatXrRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface PolicyRouteChildren {
  PolicyPrivacyRoute: typeof PolicyPrivacyRoute
  PolicyTermsRoute: typeof PolicyTermsRoute
}

const PolicyRouteChildren: PolicyRouteChildren = {
  PolicyPrivacyRoute: PolicyPrivacyRoute,
  PolicyTermsRoute: PolicyTermsRoute,
}

const PolicyRouteWithChildren =
  PolicyRoute._addFileChildren(PolicyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
  GoodbyeRoute: GoodbyeRoute,
  PolicyRoute: PolicyRouteWithChildren,
  ApiMailRoute: ApiMailRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
