/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PolicyRouteImport } from './app/policy'
import { Route as GoodbyeRouteImport } from './app/goodbye'
import { Route as ChatRouteImport } from './app/_chat'
import { Route as AuthRouteImport } from './app/_auth'
import { Route as ChatIndexRouteImport } from './app/_chat/index'
import { Route as PolicyTermsRouteImport } from './app/policy/terms'
import { Route as PolicyPrivacyRouteImport } from './app/policy/privacy'
import { Route as ApiUploadthingRouteImport } from './app/api/uploadthing'
import { Route as ApiMailRouteImport } from './app/api/mail'
import { Route as ChatXrRouteImport } from './app/_chat/xr'
import { Route as ChatSettingsRouteImport } from './app/_chat/settings'
import { Route as ChatPricingRouteImport } from './app/_chat/pricing'
import { Route as ChatNewRouteImport } from './app/_chat/new'
import { Route as AuthSignUpRouteImport } from './app/_auth/sign-up'
import { Route as AuthLoginRouteImport } from './app/_auth/login'
import { Route as ChatSettingsIndexRouteImport } from './app/_chat/settings/index'
import { Route as ChatSettingsPreferencesRouteImport } from './app/_chat/settings/preferences'
import { Route as ChatSettingsContactRouteImport } from './app/_chat/settings/contact'
import { Route as ChatSettingsAccountRouteImport } from './app/_chat/settings/account'
import { Route as ChatChatIdRouteImport } from './app/_chat/chat.$id'

const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodbyeRoute = GoodbyeRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const PolicyTermsRoute = PolicyTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PolicyRoute,
} as any)
const PolicyPrivacyRoute = PolicyPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PolicyRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailRoute = ApiMailRouteImport.update({
  id: '/api/mail',
  path: '/api/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatXrRoute = ChatXrRouteImport.update({
  id: '/xr',
  path: '/xr',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPricingRoute = ChatPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ChatRoute,
} as any)
const ChatNewRoute = ChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ChatRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ChatSettingsIndexRoute = ChatSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatSettingsRoute,
} as any)
const ChatSettingsPreferencesRoute = ChatSettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ChatSettingsRoute,
} as any)
const ChatSettingsContactRoute = ChatSettingsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ChatSettingsRoute,
} as any)
const ChatSettingsAccountRoute = ChatSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ChatSettingsRoute,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/goodbye': typeof GoodbyeRoute
  '/policy': typeof PolicyRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/new': typeof ChatNewRoute
  '/pricing': typeof ChatPricingRoute
  '/settings': typeof ChatSettingsRouteWithChildren
  '/xr': typeof ChatXrRoute
  '/api/mail': typeof ApiMailRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/policy/privacy': typeof PolicyPrivacyRoute
  '/policy/terms': typeof PolicyTermsRoute
  '/chat/$id': typeof ChatChatIdRoute
  '/settings/account': typeof ChatSettingsAccountRoute
  '/settings/contact': typeof ChatSettingsContactRoute
  '/settings/preferences': typeof ChatSettingsPreferencesRoute
  '/settings/': typeof ChatSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ChatIndexRoute
  '/goodbye': typeof GoodbyeRoute
  '/policy': typeof PolicyRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/new': typeof ChatNewRoute
  '/pricing': typeof ChatPricingRoute
  '/xr': typeof ChatXrRoute
  '/api/mail': typeof ApiMailRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/policy/privacy': typeof PolicyPrivacyRoute
  '/policy/terms': typeof PolicyTermsRoute
  '/chat/$id': typeof ChatChatIdRoute
  '/settings/account': typeof ChatSettingsAccountRoute
  '/settings/contact': typeof ChatSettingsContactRoute
  '/settings/preferences': typeof ChatSettingsPreferencesRoute
  '/settings': typeof ChatSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_chat': typeof ChatRouteWithChildren
  '/goodbye': typeof GoodbyeRoute
  '/policy': typeof PolicyRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_chat/new': typeof ChatNewRoute
  '/_chat/pricing': typeof ChatPricingRoute
  '/_chat/settings': typeof ChatSettingsRouteWithChildren
  '/_chat/xr': typeof ChatXrRoute
  '/api/mail': typeof ApiMailRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/policy/privacy': typeof PolicyPrivacyRoute
  '/policy/terms': typeof PolicyTermsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/chat/$id': typeof ChatChatIdRoute
  '/_chat/settings/account': typeof ChatSettingsAccountRoute
  '/_chat/settings/contact': typeof ChatSettingsContactRoute
  '/_chat/settings/preferences': typeof ChatSettingsPreferencesRoute
  '/_chat/settings/': typeof ChatSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goodbye'
    | '/policy'
    | '/login'
    | '/sign-up'
    | '/new'
    | '/pricing'
    | '/settings'
    | '/xr'
    | '/api/mail'
    | '/api/uploadthing'
    | '/policy/privacy'
    | '/policy/terms'
    | '/chat/$id'
    | '/settings/account'
    | '/settings/contact'
    | '/settings/preferences'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/goodbye'
    | '/policy'
    | '/login'
    | '/sign-up'
    | '/new'
    | '/pricing'
    | '/xr'
    | '/api/mail'
    | '/api/uploadthing'
    | '/policy/privacy'
    | '/policy/terms'
    | '/chat/$id'
    | '/settings/account'
    | '/settings/contact'
    | '/settings/preferences'
    | '/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/_chat'
    | '/goodbye'
    | '/policy'
    | '/_auth/login'
    | '/_auth/sign-up'
    | '/_chat/new'
    | '/_chat/pricing'
    | '/_chat/settings'
    | '/_chat/xr'
    | '/api/mail'
    | '/api/uploadthing'
    | '/policy/privacy'
    | '/policy/terms'
    | '/_chat/'
    | '/_chat/chat/$id'
    | '/_chat/settings/account'
    | '/_chat/settings/contact'
    | '/_chat/settings/preferences'
    | '/_chat/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
  GoodbyeRoute: typeof GoodbyeRoute
  PolicyRoute: typeof PolicyRouteWithChildren
  ApiMailRoute: typeof ApiMailRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodbye': {
      id: '/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof GoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/policy/terms': {
      id: '/policy/terms'
      path: '/terms'
      fullPath: '/policy/terms'
      preLoaderRoute: typeof PolicyTermsRouteImport
      parentRoute: typeof PolicyRoute
    }
    '/policy/privacy': {
      id: '/policy/privacy'
      path: '/privacy'
      fullPath: '/policy/privacy'
      preLoaderRoute: typeof PolicyPrivacyRouteImport
      parentRoute: typeof PolicyRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail': {
      id: '/api/mail'
      path: '/api/mail'
      fullPath: '/api/mail'
      preLoaderRoute: typeof ApiMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/xr': {
      id: '/_chat/xr'
      path: '/xr'
      fullPath: '/xr'
      preLoaderRoute: typeof ChatXrRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pricing': {
      id: '/_chat/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ChatPricingRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/new': {
      id: '/_chat/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof ChatNewRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_chat/settings/': {
      id: '/_chat/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ChatSettingsIndexRouteImport
      parentRoute: typeof ChatSettingsRoute
    }
    '/_chat/settings/preferences': {
      id: '/_chat/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof ChatSettingsPreferencesRouteImport
      parentRoute: typeof ChatSettingsRoute
    }
    '/_chat/settings/contact': {
      id: '/_chat/settings/contact'
      path: '/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof ChatSettingsContactRouteImport
      parentRoute: typeof ChatSettingsRoute
    }
    '/_chat/settings/account': {
      id: '/_chat/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ChatSettingsAccountRouteImport
      parentRoute: typeof ChatSettingsRoute
    }
    '/_chat/chat/$id': {
      id: '/_chat/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ChatSettingsRouteChildren {
  ChatSettingsAccountRoute: typeof ChatSettingsAccountRoute
  ChatSettingsContactRoute: typeof ChatSettingsContactRoute
  ChatSettingsPreferencesRoute: typeof ChatSettingsPreferencesRoute
  ChatSettingsIndexRoute: typeof ChatSettingsIndexRoute
}

const ChatSettingsRouteChildren: ChatSettingsRouteChildren = {
  ChatSettingsAccountRoute: ChatSettingsAccountRoute,
  ChatSettingsContactRoute: ChatSettingsContactRoute,
  ChatSettingsPreferencesRoute: ChatSettingsPreferencesRoute,
  ChatSettingsIndexRoute: ChatSettingsIndexRoute,
}

const ChatSettingsRouteWithChildren = ChatSettingsRoute._addFileChildren(
  ChatSettingsRouteChildren,
)

interface ChatRouteChildren {
  ChatNewRoute: typeof ChatNewRoute
  ChatPricingRoute: typeof ChatPricingRoute
  ChatSettingsRoute: typeof ChatSettingsRouteWithChildren
  ChatXrRoute: typeof ChatXrRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatNewRoute: ChatNewRoute,
  ChatPricingRoute: ChatPricingRoute,
  ChatSettingsRoute: ChatSettingsRouteWithChildren,
  ChatXrRoute: ChatXrRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatChatIdRoute: ChatChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface PolicyRouteChildren {
  PolicyPrivacyRoute: typeof PolicyPrivacyRoute
  PolicyTermsRoute: typeof PolicyTermsRoute
}

const PolicyRouteChildren: PolicyRouteChildren = {
  PolicyPrivacyRoute: PolicyPrivacyRoute,
  PolicyTermsRoute: PolicyTermsRoute,
}

const PolicyRouteWithChildren =
  PolicyRoute._addFileChildren(PolicyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
  GoodbyeRoute: GoodbyeRoute,
  PolicyRoute: PolicyRouteWithChildren,
  ApiMailRoute: ApiMailRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
