/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as TermsOfServiceRouteImport } from './app/terms-of-service'
import { Route as SsoCallbackRouteImport } from './app/sso-callback'
import { Route as PrivacyPolicyRouteImport } from './app/privacy-policy'
import { Route as GoodbyeRouteImport } from './app/goodbye'
import { Route as ChatRouteImport } from './app/_chat'
import { Route as ChatIndexRouteImport } from './app/_chat/index'
import { Route as ApiUploadthingRouteImport } from './app/api/uploadthing'
import { Route as ApiMailRouteImport } from './app/api/mail'
import { Route as ChatPricingRouteImport } from './app/_chat/pricing'
import { Route as ChatAuthenticatedRouteImport } from './app/_chat/_authenticated'
import { Route as ChatAuthenticatedSettingsRouteImport } from './app/_chat/_authenticated/settings'
import { Route as ChatAuthenticatedNewRouteImport } from './app/_chat/_authenticated/new'
import { Route as ChatAuthenticatedSettingsIndexRouteImport } from './app/_chat/_authenticated/settings/index'
import { Route as ChatAuthenticatedSettingsPreferencesRouteImport } from './app/_chat/_authenticated/settings/preferences'
import { Route as ChatAuthenticatedSettingsContactRouteImport } from './app/_chat/_authenticated/settings/contact'
import { Route as ChatAuthenticatedSettingsAccountRouteImport } from './app/_chat/_authenticated/settings/account'
import { Route as ChatAuthenticatedChatIdRouteImport } from './app/_chat/_authenticated/chat.$id'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodbyeRoute = GoodbyeRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailRoute = ApiMailRouteImport.update({
  id: '/api/mail',
  path: '/api/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPricingRoute = ChatPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAuthenticatedRoute = ChatAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAuthenticatedSettingsRoute =
  ChatAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ChatAuthenticatedRoute,
  } as any)
const ChatAuthenticatedNewRoute = ChatAuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ChatAuthenticatedRoute,
} as any)
const ChatAuthenticatedSettingsIndexRoute =
  ChatAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChatAuthenticatedSettingsRoute,
  } as any)
const ChatAuthenticatedSettingsPreferencesRoute =
  ChatAuthenticatedSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => ChatAuthenticatedSettingsRoute,
  } as any)
const ChatAuthenticatedSettingsContactRoute =
  ChatAuthenticatedSettingsContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => ChatAuthenticatedSettingsRoute,
  } as any)
const ChatAuthenticatedSettingsAccountRoute =
  ChatAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => ChatAuthenticatedSettingsRoute,
  } as any)
const ChatAuthenticatedChatIdRoute = ChatAuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => ChatAuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/goodbye': typeof GoodbyeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/pricing': typeof ChatPricingRoute
  '/api/mail': typeof ApiMailRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/new': typeof ChatAuthenticatedNewRoute
  '/settings': typeof ChatAuthenticatedSettingsRouteWithChildren
  '/chat/$id': typeof ChatAuthenticatedChatIdRoute
  '/settings/account': typeof ChatAuthenticatedSettingsAccountRoute
  '/settings/contact': typeof ChatAuthenticatedSettingsContactRoute
  '/settings/preferences': typeof ChatAuthenticatedSettingsPreferencesRoute
  '/settings/': typeof ChatAuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/goodbye': typeof GoodbyeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/': typeof ChatIndexRoute
  '/pricing': typeof ChatPricingRoute
  '/api/mail': typeof ApiMailRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/new': typeof ChatAuthenticatedNewRoute
  '/chat/$id': typeof ChatAuthenticatedChatIdRoute
  '/settings/account': typeof ChatAuthenticatedSettingsAccountRoute
  '/settings/contact': typeof ChatAuthenticatedSettingsContactRoute
  '/settings/preferences': typeof ChatAuthenticatedSettingsPreferencesRoute
  '/settings': typeof ChatAuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/goodbye': typeof GoodbyeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_chat/_authenticated': typeof ChatAuthenticatedRouteWithChildren
  '/_chat/pricing': typeof ChatPricingRoute
  '/api/mail': typeof ApiMailRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/_authenticated/new': typeof ChatAuthenticatedNewRoute
  '/_chat/_authenticated/settings': typeof ChatAuthenticatedSettingsRouteWithChildren
  '/_chat/_authenticated/chat/$id': typeof ChatAuthenticatedChatIdRoute
  '/_chat/_authenticated/settings/account': typeof ChatAuthenticatedSettingsAccountRoute
  '/_chat/_authenticated/settings/contact': typeof ChatAuthenticatedSettingsContactRoute
  '/_chat/_authenticated/settings/preferences': typeof ChatAuthenticatedSettingsPreferencesRoute
  '/_chat/_authenticated/settings/': typeof ChatAuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goodbye'
    | '/privacy-policy'
    | '/sso-callback'
    | '/terms-of-service'
    | '/pricing'
    | '/api/mail'
    | '/api/uploadthing'
    | '/new'
    | '/settings'
    | '/chat/$id'
    | '/settings/account'
    | '/settings/contact'
    | '/settings/preferences'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/goodbye'
    | '/privacy-policy'
    | '/sso-callback'
    | '/terms-of-service'
    | '/'
    | '/pricing'
    | '/api/mail'
    | '/api/uploadthing'
    | '/new'
    | '/chat/$id'
    | '/settings/account'
    | '/settings/contact'
    | '/settings/preferences'
    | '/settings'
  id:
    | '__root__'
    | '/_chat'
    | '/goodbye'
    | '/privacy-policy'
    | '/sso-callback'
    | '/terms-of-service'
    | '/_chat/_authenticated'
    | '/_chat/pricing'
    | '/api/mail'
    | '/api/uploadthing'
    | '/_chat/'
    | '/_chat/_authenticated/new'
    | '/_chat/_authenticated/settings'
    | '/_chat/_authenticated/chat/$id'
    | '/_chat/_authenticated/settings/account'
    | '/_chat/_authenticated/settings/contact'
    | '/_chat/_authenticated/settings/preferences'
    | '/_chat/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  GoodbyeRoute: typeof GoodbyeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiMailRoute: typeof ApiMailRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodbye': {
      id: '/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof GoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail': {
      id: '/api/mail'
      path: '/api/mail'
      fullPath: '/api/mail'
      preLoaderRoute: typeof ApiMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/pricing': {
      id: '/_chat/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ChatPricingRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/_authenticated': {
      id: '/_chat/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatAuthenticatedRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/_authenticated/settings': {
      id: '/_chat/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatAuthenticatedSettingsRouteImport
      parentRoute: typeof ChatAuthenticatedRoute
    }
    '/_chat/_authenticated/new': {
      id: '/_chat/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof ChatAuthenticatedNewRouteImport
      parentRoute: typeof ChatAuthenticatedRoute
    }
    '/_chat/_authenticated/settings/': {
      id: '/_chat/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ChatAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof ChatAuthenticatedSettingsRoute
    }
    '/_chat/_authenticated/settings/preferences': {
      id: '/_chat/_authenticated/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof ChatAuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof ChatAuthenticatedSettingsRoute
    }
    '/_chat/_authenticated/settings/contact': {
      id: '/_chat/_authenticated/settings/contact'
      path: '/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof ChatAuthenticatedSettingsContactRouteImport
      parentRoute: typeof ChatAuthenticatedSettingsRoute
    }
    '/_chat/_authenticated/settings/account': {
      id: '/_chat/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ChatAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof ChatAuthenticatedSettingsRoute
    }
    '/_chat/_authenticated/chat/$id': {
      id: '/_chat/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatAuthenticatedChatIdRouteImport
      parentRoute: typeof ChatAuthenticatedRoute
    }
  }
}

interface ChatAuthenticatedSettingsRouteChildren {
  ChatAuthenticatedSettingsAccountRoute: typeof ChatAuthenticatedSettingsAccountRoute
  ChatAuthenticatedSettingsContactRoute: typeof ChatAuthenticatedSettingsContactRoute
  ChatAuthenticatedSettingsPreferencesRoute: typeof ChatAuthenticatedSettingsPreferencesRoute
  ChatAuthenticatedSettingsIndexRoute: typeof ChatAuthenticatedSettingsIndexRoute
}

const ChatAuthenticatedSettingsRouteChildren: ChatAuthenticatedSettingsRouteChildren =
  {
    ChatAuthenticatedSettingsAccountRoute:
      ChatAuthenticatedSettingsAccountRoute,
    ChatAuthenticatedSettingsContactRoute:
      ChatAuthenticatedSettingsContactRoute,
    ChatAuthenticatedSettingsPreferencesRoute:
      ChatAuthenticatedSettingsPreferencesRoute,
    ChatAuthenticatedSettingsIndexRoute: ChatAuthenticatedSettingsIndexRoute,
  }

const ChatAuthenticatedSettingsRouteWithChildren =
  ChatAuthenticatedSettingsRoute._addFileChildren(
    ChatAuthenticatedSettingsRouteChildren,
  )

interface ChatAuthenticatedRouteChildren {
  ChatAuthenticatedNewRoute: typeof ChatAuthenticatedNewRoute
  ChatAuthenticatedSettingsRoute: typeof ChatAuthenticatedSettingsRouteWithChildren
  ChatAuthenticatedChatIdRoute: typeof ChatAuthenticatedChatIdRoute
}

const ChatAuthenticatedRouteChildren: ChatAuthenticatedRouteChildren = {
  ChatAuthenticatedNewRoute: ChatAuthenticatedNewRoute,
  ChatAuthenticatedSettingsRoute: ChatAuthenticatedSettingsRouteWithChildren,
  ChatAuthenticatedChatIdRoute: ChatAuthenticatedChatIdRoute,
}

const ChatAuthenticatedRouteWithChildren =
  ChatAuthenticatedRoute._addFileChildren(ChatAuthenticatedRouteChildren)

interface ChatRouteChildren {
  ChatAuthenticatedRoute: typeof ChatAuthenticatedRouteWithChildren
  ChatPricingRoute: typeof ChatPricingRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatAuthenticatedRoute: ChatAuthenticatedRouteWithChildren,
  ChatPricingRoute: ChatPricingRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  GoodbyeRoute: GoodbyeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiMailRoute: ApiMailRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
